name: tca

channels:
  - defaults
  - conda-forge

dependencies:

  # test
#  - black
#  - flake8
#  - pyinstrument
  - pytest

  # run
  - python=3.8
  - pip
#  - ib-insync>=0.9.71,<1
  - lxml
  - pandas
  - pip:
      - ib-insync>=0.9.71,<1
